# Generated by Django 5.2.9 on 2026-02-03 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_user_alter_athlete_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sport',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('athlete_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='athletes.athlete')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='profile_banner/')),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('x', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('athletes.athlete',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='athletes.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.TextField(max_length=100)),
                ('performance', models.TextField(max_length=100)),
                ('highlight', models.TextField(max_length=100)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='athletes.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='Add emoji of your achievement (e.g., 🏆, 🎯, ⭐)', max_length=10, validators=[django.core.validators.RegexValidator(message='This field must contain only emojis.', regex='^[\\U00010000-\\U0010ffff\\u2600-\\u26ff\\u2700-\\u27bf]+$')])),
                ('achievement', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='athletes.profile')),
            ],
        ),
    ]
